sonar.projectKey=fiap-13soat-auto-repair-shop-billing-service
sonar.organization=fiap-13soat
sonar.projectName=Billing & Payment Service

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
