apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: billing-service
